### ISSUE TITLE
This "sample" doesn't have an application component.

### ISSUE THREAD

**Issue by missmah** [Microsoft/Windows-classic-samples#1]
This "sample" just builds a DLL. There's no documentation, and no sample showing how to use the DLL.

Fail.

**Comment by oldnewthing** [comment]
Can you be more specific? Which sample are you referring to?

**Comment by sdaly2324** [comment]
DX11VideoRenderer for me.

**Comment by sdaly2324** [comment]
Figured it out.
Register the renderer
Regsvr32.exe DX11VideoRenderer.dll

Launch topoedit.exe, the newest, old ones do not work.
For me it was 
"X:\Program Files (x86)\Windows Kits\10\bin\x86\topoedit.exe"

In TopoEdit, in the Topology menu you should now see "Add DX11 Video Renederer"

Use VS to attach to process... then you can start hitting some break points.

BTW window resizing is busted.

**Comment by ChrisGuzak** [comment]
please create a separate issue for window resizing if you want.
