### ISSUE TITLE
CloudProvider status update

### ISSUE THREAD

**Issue by tzulea** [microsoft/Windows-classic-samples#100]
I have a question related to Placeholder and regular files:
How to update manually the status of an item CloudProvider sample ?

Scenario:
If a placeholder is converted to regular file, the status is changed to Sync pending.
It will be preferred to remove the status and the icon altogether from the regular file,
or a functionality to update the sync status without converting the file back to the placeholder.
Thanks.

**Comment by oldnewthing** [comment]
I've asked the sample owner if this is a scenario worth adding to the sample.

**Comment by luedersj** [comment]
Any file under a sync root that is not a placeholder is assume to be pending upload. If you want to have the system not consider the file for sync you need to exclude the file. This is done by setting FILE_ATTRIBUTE_PINNED and FILE_ATTRIBUTE_UNPINNED on the file.
