### ISSUE TITLE
Memory leak in codesigning sample

### ISSUE THREAD

**Issue by analyze-v** [microsoft/Windows-classic-samples#101]
Samples/Security/CodeSigning/cpp/codesigning.cpp

The call to CryptCATAdminReleaseCatalogContext on line 265 will never be called because CatInfoHandle will always be NULL (from line 247)

**Comment by oldnewthing** [comment]
This is not a leak. CryptCATAdminEnumCatalogFromHash destroys the old CatInfoHandle when it returns a new one. The "if" in the Cleanup is to deal with the early exit when CryptCATCatalogInfoFromContext fails. In that case, the loop exits with a non-null CatInfoHandle that needs to be cleaned up.
