### ISSUE TITLE
CloudMirror doesn't debug out of the box

### ISSUE THREAD

**Issue by jamesmcguirepro** [microsoft/Windows-classic-samples#102]
I need to set the CloudMirrorPackage's properties to "Native only" for both Application Process and Background task process

**Comment by oldnewthing** [comment]
I've asked the sample author to investigate.

**Comment by oldnewthing** [comment]
The trick to debugging CloudMirror is not to launch it from Visual Studio. Instead, launch it from the Start menu, and then use "Attach to Process" to connect the debugger.
