### ISSUE TITLE
BCryptImportKeyPair import key failed when key type is LEGACY_RSAPUBLIC_BLOB

### ISSUE THREAD

**Issue by laizewei** [microsoft/Windows-classic-samples#104]
BCryptOpenAlgorithmProvider (CngRsaHandle, BCRYPT_RSA_ALGORITHM, NULL, 0);
status=BCryptImportKeyPair (CngRsaHandle, 0, LEGACY_RSAPUBLIC_BLOB, CapiKeyHandle, KeyBlob, cbKeyBlob, 0);

ths status is STATUS_NOT_SUPPORTED?

**Comment by oldnewthing** [comment]
The code you provided does not appear in any sample in this repo.
