### ISSUE TITLE
How to calculate SM2 elliptic curves by using CNG API

### ISSUE THREAD

**Issue by laizewei** [microsoft/Windows-classic-samples#109]
the Chinese SM2 standard:     https://tools.ietf.org/html/draft-shen-sm2-ecdsa-02

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample that is not working. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “Forums & Community” section choose "Desktop Applications".
