### ISSUE TITLE
RadialController cpp - Run As Administrator

### ISSUE THREAD

**Issue by IChickenNugget** [Microsoft/Windows-classic-samples#11]
Hi,

I’m running into some issues with the dial when the application is **running as administrator**.

Using the sample classic Desktop Sample App: https://github.com/Microsoft/Windows-classic-samples/tree/master/Samples/RadialController/cpp

It seems that many of the callbacks registered stop working as a result of the application being run as administrator.

For example, a number of callbacks no longer get called when registered with:
IRadialControllerInterop::add_ControlLost
IRadialControllerInterop::add_ControlAcquired
IRadialControllerInterop::add_RotationChanged
...
Etc.

The registration of the above callbacks appear to succeed when looking at the HRESULT.

The only callback that seems to be working when running as administrator is the callback registered via IRadialControllerMenuItem::add_Invoked.

Lawrence

**Comment by oldnewthing** [comment]
Thanks for the report. The team is investigating now.

**Comment by oldnewthing** [comment]
The team has confirmed that this is a bug and is looking into how to fix it. Thanks for reporting it.

**Comment by IChickenNugget** [comment]
Thank you!
