### ISSUE TITLE
Missing dlls when starting MFCaptureToFile

### ISSUE THREAD

**Issue by strentler** [microsoft/Windows-classic-samples#110]
Hi,
i compiled (after converting the solution and projects to VS2019) the sample MFCaptureToFile.

SDK is version: 10.0.18362.0

After starting the comiled exe i get a message box telling me of several missing dlls.

For example it tells me three is a missing mf.dll or mfplat.dll.

I am running on Windows 10 Enterprise N (1809).
Is my OS an issue?

**Comment by hsebs** [comment]
It looks like your OS problem.

It works well in my computer.

My env :
* Visual Studio 2017 Community
* Win 10 SDK 10.0.17763.0
* Windows 10 Education

**Comment by oldnewthing** [comment]
The N systems do not have multimedia components. That's what the N means.
