### ISSUE TITLE
redeclaration warning for variable "i" is treated as an error.

### ISSUE THREAD

**Issue by Drake-Wu** [microsoft/Windows-classic-samples#111]
https://github.com/microsoft/Windows-classic-samples/blob/master/Samples/Win7Samples/winui/shell/shellextensibility/explorerdataprovider/Category.cpp#L742
redeclaration warning for variable "i" is treated as an error.
build with vs2019.
should be improved as:
`for (int j = 0; j < ARRAYSIZE(rgNames); j++)
{
         CoTaskMemFree(rgNames[j]);
}`

**Comment by oldnewthing** [comment]
Will be fixed in 2/24/2021 update. Thanks.
