### ISSUE TITLE
SimpleDirect2dApplication could crash in 64 bit environment

### ISSUE THREAD

**Issue by gldhnchn** [microsoft/Windows-classic-samples#112]
There is a problem with this line https://github.com/microsoft/Windows-classic-samples/blob/cc41cff4eb9c3443694893e4dd5ddaddd9a67437/Samples/Win7Samples/multimedia/Direct2D/SimpleDirect2DApplication/SimpleDirect2dApplication.cpp#L560

When `pDemoApp` is a address greater than 32 bits `PtrToUlong` drops the upper half of that pointer and the application will crash. At least that happend in my application. I replaced the line with the following to fix this bug:
```
reinterpret_cast<LONG_PTR>(pDemoApp)
```

**Comment by oldnewthing** [comment]
Fixed in PR, thanks.
