### ISSUE TITLE
Differential backup option (ad) is not shown for windows server 2016 standard 64bit OS

### ISSUE THREAD

**Issue by subodh2691** [microsoft/Windows-classic-samples#113]
I wanted to take Full and Diff backups from SqlServerWriter using vshadow. I am successfully able to take full but unable to take diff's as -ad option is not shown. Can you please help?
Microsoft Visual Studio Community 2019 used to build solution

**Comment by oldnewthing** [comment]
This appears to be a question about the OS itself and not any particular sample. You can ask your question on the [Windows developer forums](https://social.msdn.microsoft.com/Forums/Windowsdesktop).
