### ISSUE TITLE
Query: Is this a move or copy-paste operation

### ISSUE THREAD

**Issue by KrupalJoshi** [microsoft/Windows-classic-samples#115]
Hi,

You are using "Msvm_VirtualSystemMigrationService" class for migration of VMs.

So, is this a VMs (disk files/vhdx and cofig files) move or copy-paste operation (from source to destination)?

**Comment by oldnewthing** [comment]
Sorry, most of the samples were simply copied from older SDKs. If you have questions about the OS features demonstrated by the samples, you can ask on the [developer support forums](https://social.msdn.microsoft.com/Forums/Windowsdesktop).
