### ISSUE TITLE
I Can't launch example of DeskBands. It has too ugly instruction in readme.

### ISSUE THREAD

**Issue by johnynsk** [microsoft/Windows-classic-samples#122]
Today I have tried to launch the DeskBands sample, which is located by the path: https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples/winui/shell/shellextensibility/deskbands.

I had cloned the repository and then compiles it with the Microsoft Visual Studio Community 2019.

This project has the following README:
```
Illustrates the use of the different DeskBand API APIs to create a custom desk band.

Build and register DeskBandSDKSample.dll and right-click on the Task Bar, expand "Toolbars" menu option and choose "DeskBand Sample".  You will see the newly created Desk Band show up on the Task Bar.
```

There are no instructions or links to the related topics (build and register the DLL).
I had tried to register compiled DLL file via the .Net 2.0 regasm utility and have the following problem:

```
c:\Users\user\projects\Windows-classic-samples\Samples\Win7Samples\winui\shell\shellextensibility\deskbands\Win32\Debug>c:\Windows\Microsoft.NET\Framework64\v2.0.50727\RegAsm.exe ./DeskbandSDKSample.dll
Microsoft (R) .NET Framework Assembly Registration Utility 2.0.50727.8922
Copyright (C) Microsoft Corporation 1998-2004.  All rights reserved.

RegAsm : error RA0000 : Failed to load 'c:\Users\evasilev\projects\Windows-classic-samples\Samples\Win7Samples\winui\shell\shellextensibility\deskbands\Win32\Debug\DeskbandSDKSample.dll' because it is not a valid .NET assembly
```
```
c:\Users\evasilev\projects\Windows-classic-samples\Samples\Win7Samples\winui\shell\shellextensibility\deskbands\x64\Release>"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\gacutil.exe" /i DeskbandSDKSample.dll
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failure adding assembly to the cache:   The module was expected to contain an assembly manifest.

```
Can you help me with the instruction (how to build and launch this sample)?

**Comment by oldnewthing** [comment]
Registration of Win32 DLLs is done with regsvr32. However, I'm not sure DeskBands work in Windows 10. This is an old Windows 7 sample.

**Comment by johnynsk** [comment]
Thank you @oldnewthing!

It helped me and the sample does works in Windows 10 (1803) with the 10 SDK.

![image](https://user-images.githubusercontent.com/4446624/76134878-92860f00-6054-11ea-9c56-2f217f95d76c.png)

**Comment by Fcoys** [comment]
![WeChat Screenshot_20220215193721](https://user-images.githubusercontent.com/31472427/154054776-36fd7531-a668-4e57-8a49-dedeec1a6ef9.png)
