### ISSUE TITLE
Add USN handling sample to CloudFilterApi sample

### ISSUE THREAD

**Issue by LokiMidgard** [microsoft/Windows-classic-samples#126]
I'm trying to utelize usn values when setting the Sync state.

However, the output is either the input USN or zero. I also tried to use the USN value provided via `fsutil usn readdata` but this still returns an error that the file is not syncronized.

**Comment by LokiMidgard** [comment]
I tried to make a sample as short as possible.
I create a Placeholder (getting an USN from that) and direcly want to set it in sync.

```c++
CF_PLACEHOLDER_CREATE_INFO cloudEntry;
// Initilize cloud entry with
// CF_PLACEHOLDER_CREATE_FLAGS::CF_PLACEHOLDER_CREATE_FLAG_NONE;
// so it will not be in sync.
	auto hr = CfCreatePlaceholders(fullPath, &cloudEntry, 1, CF_CREATE_FLAGS::CF_CREATE_FLAG_NONE, NULL);

// usn is correctly set.
auto usn = cloudEntry.CreateUsn;

// open handle with write access like documentation says; OK
HANDLE fileHandle;
hr = CfOpenFileWithOplock(fullPath, CF_OPEN_FILE_FLAGS::CF_OPEN_FILE_FLAG_WRITE_ACCESS, &fileHandle);

USN tmpUsn;
tmpUsn = usn;

// call SetInSync with USN from CfCreatePlaceholders
hr = CfSetInSyncState(fileHandle, CF_IN_SYNC_STATE::CF_IN_SYNC_STATE_IN_SYNC, CF_SET_IN_SYNC_FLAGS::CF_SET_IN_SYNC_FLAG_NONE, &tmpUsn);
	
// FAILS
// hr = 0x80070179
// The File is not in sync with the cloud. (translated from german "0x80070179 : Die Datei ist nicht mit der Cloud synchronisiert. ")

// USN is same as input usn.

```

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
