### ISSUE TITLE
Reindex command calls reset instead of reindex.

### ISSUE THREAD

**Issue by edharfmann** [microsoft/Windows-classic-samples#128]
Title says it all.

**Comment by oldnewthing** [comment]
Please update with the specific sample you are referring to and reopen.

**Comment by edharfmann** [comment]
In [](https://github.com/microsoft/Windows-classic-samples/blob/master/Samples/Win7Samples/winui/WindowsSearch/CrawlScopeCommandLine/csmcmd.cpp), line 532 - Sample calls Reset instead of Reindex.  Sample is a clone of the Reset() function right above it.
