### ISSUE TITLE
Could I get some help about NSP？

### ISSUE THREAD

**Issue by wangquent** [microsoft/Windows-classic-samples#130]
Now I’m trying to develop a name space provider which reslove dns in local (such as Proxifier).But I have some confused about NSP.
First, what’s the different between name space provider and name space provider v-2;
Second, I have finish a nsp.dll(NS_DNS) by name space provider v-1, and I have called “WSCInstallNameSpace” and "WSCWriteNameSpaceOrder" to make sure my nsp.dll on the first turn. But I found that system still choice system’s resolve result rather than nsp.dll’s resolve result. Unless the domain could not be resolved by system, then nsp.dll’s resolve result could be used.
In order to return dns resolve result by my nsp.dll, so I need to disable other NSP type of NS_DNS. But I think it is not the best way.

**Comment by oldnewthing** [comment]
This appears to be a request for help writing your own progarm, not reporting an issue with a sample in this repo. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
