### ISSUE TITLE
Reindex command calls reset instead of reindex.

### ISSUE THREAD

**Issue by edharfmann** [microsoft/Windows-classic-samples#133]
In [Win7Samples/winui/WindowsSearch/CrawlScopeCommandLine](https://github.com/microsoft/Windows-classic-samples/blob/master/Samples/Win7Samples/winui/WindowsSearch/CrawlScopeCommandLine/csmcmd.cpp), line 532 - Sample calls Reset instead of Reindex. Sample is a clone of the Reset() function right above it.

(Yes, this is a duplicate of issue 128, I could not reopen that issue.)

**Comment by oldnewthing** [comment]
Will be fixed in the 2/24/2021 update. Thanks.
