### ISSUE TITLE
TSF in metro mode fail to activate!

### ISSUE THREAD

**Issue by borman3d** [microsoft/Windows-classic-samples#138]
I use Microsoft TSF sample to develop a new IME, working fine on Desktop mode, but cannot activate on metro mode,  even I set the flag  GUID_TFCAT_TIPCAP_IMMERSIVESUPPOR still not working, in metro mode on editing filed, it won't popup IME UI when getting the focus,
Any help would be appreciated.

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)

**Comment by hercule24** [comment]
Windows noob here. How do you build this with Visual Studio 2019, I also tried to install Visual Studio 2013, but the installer doesn't seem to run on Windows 10.
