### ISSUE TITLE
System-Insights not working with Custom Perf Counters

### ISSUE THREAD

**Issue by NottyNerd** [microsoft/Windows-classic-samples#140]
I currently can't add New Capabilities for my custom perf_counter. Details are shown below

Adding the Datasource below:

        DataSource perfCounter3 = new DataSource

        {

            SourceType = DataSourceType.PerfCounter,

            PerformanceCounter = new PerformanceCounterDataSource

            {

                CounterPath = "GGD",

                CounterName = "Bandwidth MB/sec",

                InstanceName = "*"                     // All instances

            },

            AggregationType = DataAggregationType.Sum,

            SeriesContext = "GGDPerfCounters"

        };

Getting the following error below when i add the custom DataSource above:

Update-InsightsCapability : System Insights failed to register one or more of data sources for capability 'GGD Capability'.
At line:1 char:1
+ Update-InsightsCapability -Name "GGD Capability" -Library "C:\GGdCapa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo          : InvalidData: (GGD Capability:String) [Update-InsightsCapability], Exception

+ FullyQualifiedErrorId : SystemInsightsError,Microsoft.SystemInsights.Management.PowerShell.UpdateInsightsCapabilityCommand

**Everything works fine if i remove this datasource and use one from PhysicalDisk.**

Also after checking Event Viewer to check the error, I see the error below:

Failed to update capability 'GGd Capability'. Enable the Debug channel to see more details.

Unknown exception when adding or updating for capability GGd Capability. Exception type: System.ServiceModel.FaultException`1[Microsoft.SystemInsights.Management.SystemInsightsError]. Reason: The creator of this fault did not specify a Reason.

https://windowsserver.uservoice.com/forums/295047-general-feedback/suggestions/39375703-issue-with-creating-system-insights-capability-for

**Comment by oldnewthing** [comment]
This doesn't appear to be a question about [the SystemInsights sample in this repo](https://github.com/microsoft/Windows-classic-samples/blob/dd0290d7f5be0e64ad3a3ddc25c72498578f463c/Samples/SystemInsights/), but rather a question about System Insights itself. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
