### ISSUE TITLE
【C++】Is there any API to set camera power line frequency ?

### ISSUE THREAD

**Issue by Sleepingbug** [microsoft/Windows-classic-samples#141]
I can't find any  C/C++ API to set camera power line frequency.
Please tell me how can I get & set camera power line frequency programmatically.
thanks

**Comment by oldnewthing** [comment]
This appears to be a question about features available in the operating system, not an issue with a sample in this repo. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
