### ISSUE TITLE
Wrapping C++ class API for Java Native Access Consumption

### ISSUE THREAD

**Issue by sblantipodi** [microsoft/Windows-classic-samples#142]
Hi guys,
I would like to use Java Native Acces to use Windows Desktop Duplication API in my java program.

JNA is super cool and it works pretty well on Windows APIs but it works only with APIs that exports their functions in C.

Is there someone who can help in wrapping IDXGIOutputDuplication::AcquireNextFrame method
in C?

**Comment by oldnewthing** [comment]
This appears to be a request for work outside the scope of this repo.
