### ISSUE TITLE
ID2D1FACTORY::GetDesktopDpi deprecated.

### ISSUE THREAD

**Issue by levuhuy1m7** [microsoft/Windows-classic-samples#147]
GetDeskTopDpi is deprecated. Microsoft suggest to use GetDpiForWindow instead. But I don't how to use this. Any helps must be appreciated !

**Comment by oldnewthing** [comment]
You can [search this repo for GetDpiForWindow](https://github.com/microsoft/Windows-classic-samples/search?q=getdpiforwindow&unscoped_q=getdpiforwindow). The [DpiAwarenessPerWindow](https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/DPIAwarenessPerWindow) sample is most relevant.
