### ISSUE TITLE
VSHADOW: revert.cpp Not Implemented call to ShouldBlockRevert

### ISSUE THREAD

**Issue by CutiePi** [Microsoft/Windows-classic-samples#15]
__Running the compiled 64bit vshadow  in administrator cmd from SDK 10.0.14393.0__
- Calling VSHADOW -revert={mySnapID}
- In the code this fonction ShouldBlockRevert is called once in revert.cpp on line 37 
- __This is the error__
![image](https://cloud.githubusercontent.com/assets/17714927/23866537/83186150-07ef-11e7-9849-8a37155528ce.png)

**Comment by oldnewthing** [comment]
As noted in the documentation, [ShouldBlockRevert is supported only on Server](https://docs.microsoft.com/en-us/windows/desktop/api/vsbackup/nf-vsbackup-shouldblockrevert). My guess is that you are running it on a client system rather than server.

**Comment by CutiePi** [comment]
Thanks for answering, I found out before but thanks :+1:
