### ISSUE TITLE
Access to the path 'AmsiProvider.dll' is denied

### ISSUE THREAD

**Issue by Yuvraj-Takey** [microsoft/Windows-classic-samples#151]
The code is working fine and even registering the DLL also using "**$regsvr32**", but once if I unRegistered the AMSI Dll using "**$regsvr32 /u**" command, I am not able to recompile my code(second time). The compiler throwing up an error "**Access to the path 'C:\Users\AMSITest\AmsiProvider.dll' is denied**"

**Comment by oldnewthing** [comment]
The file is probably still in use by PowerShell or some other program that was using your provider while it was still registered.
