### ISSUE TITLE
CloudMirror application context menus not working on windows build 18362

### ISSUE THREAD

**Issue by prabhugurusami** [microsoft/Windows-classic-samples#156]
The sample application was deployed with the package project provided on the machine.
"MenuVerbHandler_0" entry is created in the registry
Able to obtain the com object with the CLSID.
 but still the context menus are not getting displayed.

Its x64 build with windows SDK 10.0.17763.0.

**Comment by Trafo** [comment]
same issue here

**Comment by oldnewthing** [comment]
I don't understand why this is talking about `MenuVerbHandler_0`. I can find no such thing in this sample. Please reopen with more details.
