### ISSUE TITLE
Windows update 19041.685 broke the example code Placeholders.cpp#L73

### ISSUE THREAD

**Issue by TheOneRing** [microsoft/Windows-classic-samples#164]
The recent update 19041.685 broke  the example code in https://github.com/microsoft/Windows-classic-samples/blob/5d152f51dc5b3ce3d1bb50e7435496fe7b080887/Samples/CloudMirror/CloudMirror/Placeholders.cpp#L73

The code now fails with the error `Failed to create placeholder for folder\file.txt with 8007017c` for all relative paths including a folder.

A workaround for the issue is to provide the complete directory as `BaseDirectoryPath` to [`CfCreatePlaceholders `](https://docs.microsoft.com/en-us/windows/win32/api/cfapi/nf-cfapi-cfcreateplaceholders)  
and set the `RelativeFileName` of  [`CF_PLACEHOLDER_CREATE_INFO`](https://docs.microsoft.com/en-us/windows/win32/api/cfapi/ns-cfapi-cf_placeholder_create_info) to the file name only.
While the documentation can be interpreted that way, the wording and this example here were misleading.

The behavioural change in combination with bad error handling on our side has caused us quite some trouble and potential data loss for our customers.

**Comment by oldnewthing** [comment]
Thanks. The team is working on putting together an update to the sample.

**Comment by ban-dana** [comment]
On this note, any way to get more detailed information about the infamous 0x8007017c error? There seems to be some ETL logs in  %windir%\system32\LogFiles\CloudFiles, but they seem to require private pdbs.... Anything else maybe?

**Comment by oldnewthing** [comment]
Fix is out. Thanks for your patience.
