### ISSUE TITLE
IN6_IS_ADDR_LINKLOCAL  0xc0

### ISSUE THREAD

**Issue by kouzhudong** [microsoft/Windows-classic-samples#166]
WS2TCPIP_INLINE
BOOLEAN
IN6_IS_ADDR_LINKLOCAL(CONST IN6_ADDR *a)
{
    return (BOOLEAN)((a->s6_bytes[0] == 0xfe) &&
                     ((a->s6_bytes[1] & 0xc0) == 0x80)); //0xc0 ? 0x80?
}

WS2TCPIP_INLINE
BOOLEAN
IN6_IS_ADDR_SITELOCAL(CONST IN6_ADDR *a)
{
    return (BOOLEAN)((a->s6_bytes[0] == 0xfe) &&
                     ((a->s6_bytes[1] & 0xc0) == 0xc0));
}

**Comment by oldnewthing** [comment]
It's unclear what the issue is. `// 0xc0 ? 0x80?` is not a clear statement.
