### ISSUE TITLE
Can not detect touchpad by IdentifyInputSource sample

### ISSUE THREAD

**Issue by chaopeng** [Microsoft/Windows-classic-samples#18]
Hi team,

I am trying to detect the InputSource from touchpad following https://msdn.microsoft.com/en-US/library/windows/desktop/hh448795 and the IdentifyInputSource sample. Here is my repo https://github.com/chaopeng/IdentifyInputSource. I did change 2 place:

1. Change windows version https://github.com/chaopeng/IdentifyInputSource/blob/master/cpp/stdafx.h#L10
2. Change event handler https://github.com/chaopeng/IdentifyInputSource/blob/master/cpp/InputSource.cpp#L159

I run it with surfacebook, win10 and vs2017. But when I move pointer with touchpad, the InputSource shows mouse. Am I missing something else? Also can team update the sample please? 

Thank you.
Chao

**Comment by chaopeng** [comment]
@IrinVoso , hi I think you are the best guy for this issue. If it's not you, please point to an appropriate developer, thanks.

**Comment by oldnewthing** [comment]
This is a question about the platform, not the sample. You can ask the question on the [Desktop development forum](https://social.msdn.microsoft.com/Forums/Windowsdesktop/en-us/home).
