### ISSUE TITLE
Undocumented property in cloud mirror

### ISSUE THREAD

**Issue by LokiMidgard** [microsoft/Windows-classic-samples#184]
The cloud mirror sample defines an undocumented property.

https://github.com/microsoft/Windows-classic-samples/blob/27ffb0811ca761741502feaefdb591aebf592193/Samples/CloudMirror/CloudMirror/Utilities.cpp#L15

I'm not able to find in any doc :(

If someone knows where it is documented, I search a way to set a file in the cloud mirror to error state and hoping wherever this is documented, there may be also a hint how to archive this.

**Comment by oldnewthing** [comment]
Thanks for calling this out. I've brought this to the attention of the sample author.

**Comment by wangfu91** [comment]
> I search a way to set a file in the cloud mirror to error state and hoping wherever this is documented, there may be also a hint how to archive this.

@LokiMidgard  FYI, there is an open PR #154 demoing how to set the error state using `PKEY_LastSyncError`, it might be what you want.

**Comment by oldnewthing** [comment]
The property key PKEY_StorageProviderTransferProgress is now documented in SDK versions 25131 and higher.
