### ISSUE TITLE
CloudMirror: errors 0x8007017c, 0x80028ca0 hydrating 20GB file

### ISSUE THREAD

**Issue by kelogs** [microsoft/Windows-classic-samples#185]
Hello,

I am having problems with large files. Got the sample here, modified per my needs:

- switched the SDK in CloudMirror.vcxproj to: 
    `<WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>`
- 4096 bytes chunks were not enough for large files hydrations in a timely manner so I have modified that line in FileCopierWithProgress.cpp
`     #define CHUNKSIZE (4096 * 1024)`

Building with VS2019 Community Edition v 16.9.2. Deploying on a VM (see picture) and attempting hydration of an ~20GB file and always getting "0x8007017c The cloud operation is invalid" before data transfer completes. There also is a ~2GB file that gets transferred almost fine (after the transfer completes a popup dialog shows "RPC server unavailable" or something like that). Both files are created by means of `fsutil file createnew` commands. I wonder what is going on.

Thank you

![CludMirrorSample_issue1](https://user-images.githubusercontent.com/707453/114940003-db101e80-9e49-11eb-8a53-355a3fb25da5.png)

**Comment by oldnewthing** [comment]
I've opened a ticket against the feature team.

**Comment by kelogs** [comment]
Ok, so... tried it on a non-VM Windows 10 machine, same result.

**Comment by oldnewthing** [comment]
The feature team has informed me that Cloud Mirror does not support very large files (larger than 8GB), and there are no immediate plans to address that limitation.
