### ISSUE TITLE
AMSI Not working in Windows Server 2012

### ISSUE THREAD

**Issue by kirubaKaranT** [microsoft/Windows-classic-samples#187]
hi , 
AMSI is not working in windows  Server 2012 and  Server 2012 R2
Note : i already updated my powershell to 5.1

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
