### ISSUE TITLE
CloudMirror sample crashes if a previously used location does not exist any more on the disk

### ISSUE THREAD

**Issue by smourier** [microsoft/Windows-classic-samples#194]
CloudMirror sample crashes if a previously used location does not exist any more on the disk. So, this code in ProviderFolderLocations.cpp:
	
    winrt::check_hresult(SHCreateItemFromParsingName(lastLocation.c_str(), nullptr, __uuidof(lastItem), lastItem.put_void()));
    winrt::check_hresult(fileOpen->SetFolder(lastItem.get()));

Should be replaced by something like:
	
    if (SUCCEEDED(SHCreateItemFromParsingName(lastLocation.c_str(), nullptr, __uuidof(lastItem), lastItem.put_void())))
    {
        winrt::check_hresult(fileOpen->SetFolder(lastItem.get()));
    }

**Comment by oldnewthing** [comment]
Fixed in most recent update. Thanks for the report and fix.
