### ISSUE TITLE
DNS Service Discovery

### ISSUE THREAD

**Issue by AhmedX6** [Microsoft/Windows-classic-samples#20]
Hello,

I would like to use DNS Service Discovery in C++/CLR Windows App.
I inclueded Bonjour API of Apple but I got an error `warning LNK4248: unresolved typeref token (0100002B) for '_DNSServiceRef_t'; image may not run`
It's because of CLR... I don't know how to fix this..
I saw that Microsoft got headers already included of dns service discovery.
Please can you give me some advice ? How can I do ?
Thank you !

**Comment by oldnewthing** [comment]
This isn't a question about any of the samples in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
