### ISSUE TITLE
RecipeThumbnailProvider fails to register

### ISSUE THREAD

**Issue by amberream** [microsoft/Windows-classic-samples#209]
I'm working with the project found here: Windows-classic-samples\Samples\Win7Samples\winui\shell\appshellintegration\RecipeThumbnailProvider

When I build the debug version I can register the dll, but the thumbnails are not generated.  In the code in DLL.ccp in DllRegisterServer it looks like I should expect to see 4 registry entries, but I'm only getting the last one:

```
        const REGISTRY_ENTRY rgRegistryEntries[] =
        {
            // RootKey            KeyName                                                                ValueName                     Data
            {HKEY_CURRENT_USER,   L"SOFTWARE\\Classes\\CLSID\\" SZ_CLSID_QOPPAPDFTHUMBHANDLER,                                 NULL,                           SZ_QOPPAPDFTHUMBHANDLER},
            {HKEY_CURRENT_USER,   L"SOFTWARE\\Classes\\CLSID\\" SZ_CLSID_QOPPAPDFTHUMBHANDLER L"\\InProcServer32",             NULL,                           szModuleName},
            {HKEY_CURRENT_USER,   L"SOFTWARE\\Classes\\CLSID\\" SZ_CLSID_QOPPAPDFTHUMBHANDLER L"\\InProcServer32",             L"ThreadingModel",              L"Apartment"},
            {HKEY_CURRENT_USER,   L"SOFTWARE\\Classes\\.pdf\\ShellEx\\{e357fccd-a995-4576-b01f-234630154e96}",            NULL,                           SZ_CLSID_QOPPAPDFTHUMBHANDLER},
        };
```

When I build the release version I get an error registering the dll, "DllRegisterServer was not found."

To register, I am going to the directory they are produced in and running, "regsvr32.exe RecipeThumbnailProvider.dll".

Am I missing something?  Is there something else I need to do to successfully register this dll & get it to generate the thumbnails?  I'm on Windows 10.  Would be great if the [article](https://docs.microsoft.com/en-us/windows/win32/shell/thumbnail-providers) related to this project could be updated.

I added some debugging in the form of logging & writing the thumbnail out to a file.  When the debug dll is registered, I call my IThumbnailProvider from the [Using Thumbnail Providers Sample](https://docs.microsoft.com/en-us/windows/win32/shell/samples-usingthumbnailproviders) and I can see the log & image getting written out.  However, when I just open windows explorer and look at a file with my extension, my IThumbnailProvider is not triggered.  What is going on?

**Comment by oldnewthing** [comment]
Don't forget that you have to build the version that matches your OS. Since you're probably running 64-bit Windows, you need to build the 64-bit DLL.

**Comment by oldnewthing** [comment]
You probably built "Using Thumbnail Providers Sample" as win32 (matching the provider DLL) - that's why it works.

If regsvr32 cannot load the DLL then certainly Explorer can't load it either. You can try debugging regsvr32 - set a breakpoint on LoadLibraryW and LoadLibraryExW, see what it returns. Alternatively, write your own 64-bit program that does a LoadLibrary("yourdll.dll").
