### ISSUE TITLE
Location of the center of the zoom in GID_ZOOM Gesture

### ISSUE THREAD

**Issue by prashantkn94** [Microsoft/Windows-classic-samples#21]
Hi,
when the fingers move while zooming, they either move towards each other(zoom out) or move apart from each other(zoom in). In case of ANY movement other than these the zoom gesture should end. [https://github.com/Microsoft/Windowsclassicsamples/blob/master/Samples/Win7Samples/Touch/MTGestures/cpp/GestureEngine.cpp]() 
Though this sample re-calculates the center of the zoom every time until it receives GF_END message. So, where does the center is exactly located? , shouldn't it be exactly in between the 2 fingers in action ? but then why do we expect it to change in the phase between GF_BEGIN and GF_END ? 
Kindly help, TIA.

**Comment by oldnewthing** [comment]
Human beings are not very good at moving two fingers at *exactly* the same rate outwards. There is usually some error, which can cause the center to shift slightly. (For example, when I do a pinch gesture, my index finger moves faster than my thumb.)

**Comment by prashantkn94** [comment]
Thank you very much. This thing bothered me a lot.
