### ISSUE TITLE
Monitor will flash before shut off by use SendMessage command

### ISSUE THREAD

**Issue by yi9927226** [microsoft/Windows-classic-samples#217]
When I use "SendMessage(HWND_TOPMOST, WM_SYSCOMMAND, SC_MONITORPOWER, -2);" to shut off my monitor, monitor will flash before shut off.

I upload the problem video to [here][1].

PS: Use command "SendMessage(..)" to shut off monitor is referenced this [document][2].

  [1]: https://1drv.ms/u/s!ApvRl2wqaz_6gc1CGG8U_XnqlRBKsw?e=erPtCW
  [2]: https://docs.microsoft.com/en-us/windows/win32/menurc/wm-syscommand

**Comment by oldnewthing** [comment]
This does not appear to be an issue with any sample in this repo.
