### ISSUE TITLE
Update CloudMirror sample for CppWinRT 2 and VS2022

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/Windows-classic-samples#222]
https://github.com/microsoft/Windows-classic-samples/blob/67a8cddc25880ebc64018e833f0bf51589fd4521/Samples/CloudMirror/README.md?plain=1#L33

Objection! The sample doesn't work with VS2022, VC143 and CppWinRT 2.
Please update the CloudMirror sample to work with newer VC toolkits and CppWinRT 2.

**Comment by oldnewthing** [comment]
Upgraded!
