### ISSUE TITLE
Unable to connect to bluetooth handset from Window 7

### ISSUE THREAD

**Issue by ShivaniPahuja02** [Microsoft/Windows-classic-samples#23]
Hi ,

i am using the same sample to connect Bluetooth handset  from window 7 machine.  i am successfully able to locate and pair the Bluetooth handset, Window 7 bluetooth devices shows the handset under paired devices. but socket connect is failed always with error code 10060.

Sample is working fine on win10.

**Comment by oldnewthing** [comment]
This sounds like a platform issue (possibly hardware-related), not a sample issue. You can try asking in the [Desktop development forum](https://social.msdn.microsoft.com/Forums/Windowsdesktop/en-us/home).
