### ISSUE TITLE
MagSetWindowTransform false

### ISSUE THREAD

**Issue by jwjw2069** [microsoft/Windows-classic-samples#233]
MagSetWindowTransform is always returning false 

```
MAGTRANSFORM matrix;
				memset(&matrix, 0, sizeof(matrix)); //Clear matrix
				//n = mag factor
				matrix.v[0][0] = magnifier::magnificationFactor;
				matrix.v[1][1] = magnifier::magnificationFactor;
				matrix.v[2][2] = 1.f;
				bool factorDone = MagSetWindowTransform(magHwnd, &matrix);
				if (!factorDone) {
					Beep(200, 200);
				}
				else {
					std::cout << skCrypt("MagSetWindowTransform true") << std::endl;
				}
```

**Comment by oldnewthing** [comment]
I can't repro. Succeeds for me when I step over [this line](https://github.com/microsoft/Windows-classic-samples/blob/27ffb0811ca761741502feaefdb591aebf592193/Samples/Win7Samples/winui/magnification/CPP/MagnifierSample.cpp#L223).

The code you posted doesn't appear to be from any of the samples in this repo. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
