### ISSUE TITLE
Need License clarification please

### ISSUE THREAD

**Issue by hipersayanX** [Microsoft/Windows-classic-samples#24]
In the root of this repository it exhibit a [MIT license](https://github.com/Microsoft/Windows-classic-samples/blob/master/LICENSE), meaning all code here may be licensed under MIT license, but then going to the code, almost all code contains a [header](https://github.com/Microsoft/Windows-classic-samples/blob/master/Samples/Win7Samples/multimedia/directshow/baseclasses/amextra.cpp) with following sentence:

    // Copyright (c) 1992-2001 Microsoft Corporation.  All rights reserved.

Meaning all code is licensed under some form of EULA license.
Finally, going to [Developer code samples](https://code.msdn.microsoft.com/) at the very beginning, and then [Microsoft Developer Services Agreement](https://msdn.microsoft.com/en-US/cc300389.aspx) at the end of the document, in **Exhibit B - Microsoft Limited Public License** it states:

    This license governs use of code marked as “sample” or “example” available on this web site 
    without a license agreement, as provided under the section above titled “NOTICE SPECIFIC 
    TO SOFTWARE AVAILABLE ON THIS WEB SITE.” If you use such code (the “software”), you 
    accept this license. If you do not accept the license, do not use the software.

As when the samples was distributed with [Windows SDK](https://msdn.microsoft.com/en-us/library/ms717483(v=vs.100).aspx) (there were not any license file in there) which is now part of [Windows-classic-samples](https://github.com/Microsoft/Windows-classic-samples).

Can Microsoft clarify which license apply to the files (MIT, Ms-LPL, other?), and update code headers according to that?.

**Comment by oldnewthing** [comment]
The samples were originally published under the Microsoft public license. They have been republished under the MIT license. For archival purposes, the original samples were captured as-is (including the reference to the old license).
