### ISSUE TITLE
How to check the correctness of the username and password?

### ISSUE THREAD

**Issue by ehsanr1366** [microsoft/Windows-classic-samples#243]
I have a CP. It works well
I have added OTP to authenticate the user after entering the password. My problem is that even if the wrong password is entered, the operation continues and after entering the OTP, the user sees the wrong password message.

Is there any way to make sure the password is correct right from the start?

I used to use the 'LogonUserEx' method in the 'GetSerialization' function, but sometimes I encountered problems, for example, when the user's password expired.

**Comment by oldnewthing** [comment]
This appears to be a question about the OS, not a question about a sample in this repo. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
