### ISSUE TITLE
ApplicationLoopback - "Failed to start capture 0x80070002: The system cannot find the file specified."

### ISSUE THREAD

**Issue by ThreeDeeJay** [microsoft/Windows-classic-samples#256]
I set up [GitHub Actions](https://github.com/ThreeDeeJay/Windows-classic-samples/actions) to compile [ApplicationLoopback](https://github.com/microsoft/Windows-classic-samples/blob/main/Samples/ApplicationLoopback/README.md) (application-specific audio recorder), but when I try to run it, I get the following error:

```
Failed to start capture
0x80070002: The system cannot find the file specified.
```
[Relevant line of code](https://github.com/microsoft/Windows-classic-samples/blob/7cbd99ac1d2b4a0beffbaba29ea63d024ceff700/Samples/ApplicationLoopback/cpp/ApplicationLoopback.cpp#L68)
[Compilation log](https://github.com/ThreeDeeJay/Windows-classic-samples/actions/runs/3132993670/jobs/5085900801)
I tried with/without elevated privileges, full paths to a non-system folder and both 32/64-bit executables ([which you can download from here](https://github.com/ThreeDeeJay/Windows-classic-samples/actions/runs/3133656416))
Also in case it's relevant, I'm on Windows 10 1809 because I'm testing something, and I tried recording VLC, Firefox and other apps with the same results.
Any thoughts?

**Comment by oldnewthing** [comment]
[As noted in the README](https://github.com/microsoft/Windows-classic-samples/blob/7cbd99ac1d2b4a0beffbaba29ea63d024ceff700/Samples/ApplicationLoopback/README.md?plain=1#L41):

> Note that this sample requires Windows 10 build 20348 or later.

Version 1809 is build 17763.
