### ISSUE TITLE
crash when runing MFCaptureToFile on win10 

### ISSUE THREAD

**Issue by garrylea** [Microsoft/Windows-classic-samples#26]
hi, I have a crash when runing MFCaptureToFile on win10. I debug this program, if set  MF_SOURCE_READER_ASYNC_CALLBACK attribute, the program will crash. how to deal with?

**Comment by MaXcomX** [comment]
I just guessing: You mean within a certain function? You could be more specific, ie publish your source, so we can give an answer tio that.

**Comment by oldnewthing** [comment]
It's not clear whether you are reporting a problem with the sample in this repo, or a problem with your own app. Can you clarify? If you get a crash in the sample in this repo, can you provide more details?
