### ISSUE TITLE
Cloud Mirror Sample does not build

### ISSUE THREAD

**Issue by Cairn23** [microsoft/Windows-classic-samples#264]
I have downloaded the latest version of all the code an attempted to build.
I got the error message 
Error	MIDL2011	[msg]unresolved type declaration [context]: Windows.Storage.Provider.IStorageProviderStatusUISourceFactory [ RuntimeClass 'CloudMirror.MyStatusUISourceFactory'  ]	CloudMirror	C:\Work\Windows-classic-samples-main\Windows-classic-samples-main\Samples\CloudMirror\CloudMirror\StatusUI.idl	11	

I ensured the version of the SDK was the latest (10.0.22621.0) and reviewed previous issues with this.
This is running on Windows 10.
Any Ideas

**Comment by oldnewthing** [comment]
I cannot reproduce. Builds on my 22621.
> 1>MIDLRT Processing D:\repos\collections.classic\Samples\CloudMirror\CloudMirror\CustomStateProvider.idl
1>CustomStateProvider.idl
1>MIDLRT Processing C:\Program Files (x86)\Windows Kits\10\Include\\**10.0.22621.0**\winrt\winrtbase.idl
1>winrtbase.idl
1>MIDLRT Processing C:\Program Files (x86)\Windows Kits\10\Include\\**10.0.22621.0**\winrt\midlbase.idl
1>midlbase.idl
...
1>Processing WinMD c:\program files (x86)\windows kits\10\references\\**10.0.22621.0**\windows.storage.provider.cloudfilescontract\7.0.0.0\windows.storage.provider.cloudfilescontract.winmd
1>MIDLRT Processing D:\repos\collections.classic\Samples\CloudMirror\CloudMirror\StatusUI.idl
1>StatusUI.idl
1>MIDLRT Processing C:\Program Files (x86)\Windows Kits\10\Include\\**10.0.22621.0**\winrt\winrtbase.idl
1>winrtbase.idl
...
