### ISSUE TITLE
Why insisting on c++?

### ISSUE THREAD

**Issue by DBJDBJ** [microsoft/Windows-classic-samples#265]
[Windows classic samples are originally written in C](http://www.charlespetzold.com/blog/2014/12/The-Infamous-Windows-Hello-World-Program.html). WIN32 is the ANSI C API of an OS written in ANSI C (with extensions). For example, WIN32 hello world is pure C; including all the 10K+ lines in pure C included through `windows.h`.  Why putting it into [`main.cpp`](https://github.com/microsoft/Windows-classic-samples/tree/main/Samples/Win7Samples/begin/LearnWin32/HelloWorld)?

Why this C++ insistence?

**Comment by oldnewthing** [comment]
Each sample author chooses the language for their sample. There is no blanket policy for the repo.

**Comment by DBJDBJ** [comment]
I am sorry Raymond for being a pest and proceeding with the issue you kindly closed, but I looked into this [hello world sample I was talking about](https://github.com/microsoft/Windows-classic-samples/tree/main/Samples/Win7Samples/begin/LearnWin32/HelloWorld) again.

And, I would like to know what is programing language it was written in. It surely looks like ANSI C to me, but it is in the cpp file, thus compiled with cl.exe as c++. I can not see the C++ code in there. Maybe there is no "C++ insistence" in there?

Perhaps the good author left it as `main.cpp` accidentally?
