### ISSUE TITLE
Program should be launched from the Start Menu

### ISSUE THREAD

**Issue by begnoob123** [microsoft/Windows-classic-samples#271]
Hi,

For the CloudMirror sample, what does it mean by "This program should be launched from the Start menu, not from Visual Studio."

THank you.

**Comment by oldnewthing** [comment]
It means what is says. To run the program, open the Start menu and click "Cloud Mirror Sample". Do not use the Visual Studio "Start with debugging" or "Start without debugging" commands.

**Comment by begnoob123** [comment]
I built the Visual Studio solution as an x64 executable and shifted the executable to the Start Menu folder but it still gives me the error 'This program should be launched from the Start menu, not from Visual Studio.'.
