### ISSUE TITLE
Program cannot run

### ISSUE THREAD

**Issue by begnoob123** [microsoft/Windows-classic-samples#272]
It means what is says. To run the program, open the Start menu and click "Cloud Mirror Sample". Do not use the Visual Studio "Start with debugging" or "Start without debugging" commands.

_Originally posted by @oldnewthing in https://github.com/microsoft/Windows-classic-samples/issues/271#issuecomment-1334173524_

I built the Visual Studio solution as an x64 executable and shifted the executable to the Start Menu folder but it still gives me the error 'This program should be launched from the Start menu, not from Visual Studio.'.

**Comment by oldnewthing** [comment]
You need to deploy the MSIX package. That will put it on the Start menu (and register a bunch of other stuff as part of deployment).

**Comment by bweston92** [comment]
@begnoob123 did you manage to figure this out?

@oldnewthing the README doesn't really explain this well, how are we supposed to deploy the MSIX package.  Is this something we cannot do on a community edition of Visual Studio?

**Comment by begnoob123** [comment]
@bweston92 Hi I am not sure if you already figured it out but to deploy the msix package, simply set the the CloudMirrorPackage as the Startpp Project (Right click on CloudMirrorPackage>Set up as Startpp Project) and press F5. 
I encountered the error above when I tried to run the executable file from command line. Just press F5 in Visual Studio and it will run.
