### ISSUE TITLE
Sample ExplorerCommandVerb does not work on Windows 11

### ISSUE THREAD

**Issue by pjaholkowski** [microsoft/Windows-classic-samples#283]
Sample https://github.com/microsoft/Windows-classic-samples/tree/main/Samples/Win7Samples/winui/shell/appshellintegration/ExplorerCommandVerb does not work on Windows 11. regsvr32 successfully registers dll but the dll is not loaded when *.txt file is clicked with right mouse button (therefore verb is not shown in shell context menu).

**Comment by oldnewthing** [comment]
@ddomingos-daitan  is correct. Windows 11 moved most verbs to the "show more options" menu.

**Comment by Dave-Lowndes** [comment]
In my testing (on Win11 23H2) this doesn't work. The menu items don't show up on the main menu or in the "Show more options" menu.
