### ISSUE TITLE
Application creates shortcut in one folder but installer in another, so shortcut is not removed on uninstall

### ISSUE THREAD

**Issue by IKukhta** [Microsoft/Windows-classic-samples#31]
Installer:
https://github.com/Microsoft/Windows-classic-samples/blob/cded84bed49cb8ef2095e6470ac83ee3264c4113/Samples/DesktopToasts/CS/Product.wxs#L33

Application:
https://github.com/WindowsNotifications/desktop-toasts/blob/c171b4eb67a26aefbe03705ddeb89b6bb953855b/CS/MainWindow.xaml.cs#L65

**Comment by oldnewthing** [comment]
Sorry, I don't understand what the issue is. Are the two repos somehow related to each other?
