### ISSUE TITLE
DXGI Cpature error

### ISSUE THREAD

**Issue by soul-jh** [microsoft/Windows-classic-samples#321]
![error](https://github.com/microsoft/Windows-classic-samples/assets/58898126/7a87dcb2-3ad1-491b-8eb9-447907613d56)
The program dxgi is running in the background to obtain the screen image. When I try to open Google with the administrator permission (any program will appear), the dxgi program in the background fails to capture the image data (as shown in the figure), and the AcquireNextFrame returns 0x887A0001. Then I the re-initialization in dxgi resources, then pDxgiOutput1 - > DuplicateOutput (_d3d11Device. The Get (), _outputDuplication GetAddressOf () returns 0 x80070005.What is the solution to this problem? Thank you.

**Comment by oldnewthing** [comment]
This doesn't appear to be an issue with any sample in this repo. If you believe that it is, please specify which sample and point to a specific line number if possible.
