### ISSUE TITLE
Windows 11: Notifications vanishes after few seconds. 

### ISSUE THREAD

**Issue by sblantipodi** [microsoft/Windows-classic-samples#327]
With previous version of Windows 10 notification sticked in the Windows Notification Center forever until cancelled.

Since the latest Windows, notifications vanishes automatically after few seconds.

You can reproduce this bug by simply compiling and test your sample:

git clone --filter=blob:none --sparse https://github.com/microsoft/Windows-classic-samples.git windows-samples
cd windows-samples
git sparse-checkout add Samples/Win7Samples/winui/shell/appshellintegration/NotificationIcon

Navigate to the NotificationIcon folder and open NotificationIcon.sln in Visual Studio to compile and run it. 

Is this aYou can compile and test the sample too:

git clone --filter=blob:none --sparse https://github.com/microsoft/Windows-classic-samples.git windows-samples
cd windows-samples
git sparse-checkout add Samples/Win7Samples/winui/shell/appshellintegration/NotificationIcon

What is the right way to report this issue to Microsoft?

**Comment by oldnewthing** [comment]
You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (From "Contact Us" you can create a support incident, or you can use the forums on "Microsoft Q&A".) To file a bug, you can use the Feedback Hub app.

**Comment by sblantipodi** [comment]
Hi @oldnewthing 
thanks for the answer.

I have reported the issue to the Feedback Hub app since more than a year but it seems that no one is working on this.

What do you think about an issue on such an important API?
Notifications are very crucial to apps, isn't this something that needs more attention?

Thanks
Davide

**Comment by oldnewthing** [comment]
I do not control what the Notifications team does with their feedback.
