### ISSUE TITLE
Latest Windows Samples for MediaFoundation?

### ISSUE THREAD

**Issue by gsilva2016** [Microsoft/Windows-classic-samples#34]
These samples reference  Windows 7 and later and am trying to understand if these are the latest (maintained) samples for Win10?  I am not looking for UWP samples (I need to run as native code as these samples demonstrate).

Thank you

**Comment by oldnewthing** [comment]
I don't know whether the MediaFoundation team is using this repo for their Windows 10 samples, or whether they have some other repo.
