### ISSUE TITLE
Example of InfoTip

### ISSUE THREAD

**Issue by modz2014** [microsoft/Windows-classic-samples#352]
Hi would be create if there was an example of appending to the current InfoTip instead of overwriting it

**Comment by oldnewthing** [comment]
Can you be more specific what you are asking about? Are you saying "I wrote a custom infotip provider and after the infotip has been shown, I realize afterward that I want to add more information to it. Is there a way to tell the system to requery my infotip so I can provide the additional information?"

**Comment by modz2014** [comment]
When developing an infotip, a common concern arises regarding the ability to extend its functionality without displacing the existing content. For instance, suppose there's a desire to incorporate an additional function triggered by hovering over a text file while preserving the default information display behavior

**Comment by modz2014** [comment]
is there going to be or do I have to write the whole Infotip again that display the current information and then add to it
