### ISSUE TITLE
VbsEnclave sample returns a "800700C1 vbsenclave.dll is not a valid Win32 application." error when self-signing vbsenclave.dll file

### ISSUE THREAD

**Issue by bbonaby** [microsoft/Windows-classic-samples#364]
After walking through the example steps in here: 
https://learn.microsoft.com/en-us/windows/win32/trusted-execution/vbs-enclaves-dev-guide 

After creating my own test certificate I self-signed `vbsenclave.dll`. After building and running the app from visual studio the app starts then I get the following error: `800700C1 vbsenclave.dll is not a valid Win32 application.`

This happens on this line: https://github.com/microsoft/Windows-classic-samples/blob/d338bb385b1ac47073e3540dbfa810f4dcb12ed8/Samples/VbsEnclave/Enclave%20Host/enclapp.cpp#L67

Note: 

- I am doing this on a x64 machine, in Win 11 (Test signing turned on) and have met all the requirements listed here: https://learn.microsoft.com/en-us/windows/win32/trusted-execution/vbs-enclaves#development-prerequisites.

My expectation is that after all these pre-requistes have been met and test signing is enabled. I should be able to run the sample app without error.

**Comment by CodeMaxx** [comment]
@bbonaby Are you saying the sample code is not working or did you write your own enclave?

**Comment by bbonaby** [comment]
Whoops sorry @CodeMaxx , was suppose to close this this morning but got busy with work. I got this working last night. I believe my VM was in a bad state when I was trying this.  I created a new VM and the sample worked as expected.
