### ISSUE TITLE
If dontdisplaylastusername is turned on, loginui.exe keeps crashing with custom cred provider

### ISSUE THREAD

**Issue by aabragan** [Microsoft/Windows-classic-samples#4]
`
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"dontdisplaylastusername"=dword:00000001
`
If I enable the following setting **dontdisplaylastusername**, either through policy or by setting this registry setting and try to go to the login screen, the cursor just spins and the screen just flashes and I am never able to get the login screen to come up. Without any custom v2 credential providers installed, I am able to get to the Other User screen correctly.

How can I fix this? I tried adding a username field to my custom version since yours did not have one to see if that made any difference but that did not change anything.

Here is an example of the fault that is logged for the sample credential provider.

> Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0
Problem signature:
P1: LogonUI.exe
P2: 10.0.10586.0
P3: 5632d88c
P4: SampleV2CredentialProvider.dll
P5: 0.0.0.0
P6: 56cc64dd
P7: c0000005
P8: 0000000000003086
P9:
P10:
Attached files:
These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_LogonUI.exe_5e45fd9b49f0ea6611374ae56677dfa1cb3a1fe_9798b224_0a4ffaf8
Analysis symbol:
Rechecking for solution: 0
Report Id: 5efbdb96-de9f-4254-b259-1beea7137fc7
Report Status: 96
Faulting application name: LogonUI.exe, version: 10.0.10586.0, time stamp: 0x5632d88c
Faulting module name: SampleV2CredentialProvider.dll, version: 0.0.0.0, time stamp: 0x56cc64dd
Exception code: 0xc0000005
Fault offset: 0x0000000000003086
Faulting process id: 0x3a8
Faulting application start time: 0x01d1910e42a0efb5
Faulting application path: C:\Windows\system32\LogonUI.exe
Faulting module path: C:\Windows\system32\SampleV2CredentialProvider.dll
Report Id: 038f9265-0f6f-45fa-bc3e-6c7de490ca34
Faulting package full name:
Faulting package-relative application ID:

**Comment by oldnewthing** [comment]
Can you include a stack trace, or attach the files referenced in the event log?

**Comment by aabragan** [comment]
I reverted the lab to test a couple of different options but I will set it up again and send you the files as soon as I duplicate the issue. These will be for my credential provider, which is based on your sample.

**Comment by aabragan** [comment]
I uploaded the file as a .txt because .zip was not being accepted. rename the extension to .zip after downloading it. I am going to try to get you another crash dump from today when i can.





[AppCrash.txt](https://github.com/Microsoft/Windows-classic-samples/files/232455/AppCrash.txt)

**Comment by oldnewthing** [comment]
You need to get a stack trace with symbols that match the DLL that you built. That would tell you that the crash is in `CSampleProvider::GetCredentialAt` with `dwIndex=0`, crashing at the `_pCredential->QueryInterface(...)` because `_pCredential` is null. I'll let you pick it up from there.

**Comment by aabragan** [comment]
@oldnewthing
Thank you so much for the insight! I was able to get an updated crash dump from my latest build on Friday. Would you mind taking a look and letting me know what is going on? 

[ReportQueue for Cred Provider.txt](https://github.com/Microsoft/Windows-classic-samples/files/234676/ReportQueue.for.Cred.Provider.txt)

**Comment by aabragan** [comment]
@oldnewthing 
I did add a null  check on `_pCredential `and that seems to have resolved the crashing of the Credential Provider. Should the V2 Sample be updated with a null check too? The `GetCredentialAt `method was not modified by me at all so I assume that anyone else using the sample will run into the same problem. The code in the Credential Initialize method would also need to change to handle a scenario where the provider was initialized but without an `ICredentialProviderUser`.

What are your thoughts?

**Comment by oldnewthing** [comment]
I forwarded this issue to the sample owner. Thanks for reporting it.

**Comment by aabragan** [comment]
@oldnewthing 

Thanks for the assistance! I really appreciate it!
