### ISSUE TITLE
wrong datatype for RegisterTouchWindow

### ISSUE THREAD

**Issue by trivalik** [microsoft/Windows-classic-samples#41]
i.e. in https://github.com/Microsoft/Windows-classic-samples/blob/master/Samples/Win7Samples/Touch/MTScratchpadWMTouch/CS/WMTouchForm.cs is ulong used but MSDN https://msdn.microsoft.com/de-de/library/windows/desktop/dd317326(v=vs.85).aspx wants ULONG which is unsigned long --> 32 bit in size

This is not the only file where RegisterTouchWindow is used.

I tested this of course only with a 32 bit system or more with forces 32 bit C# application.

**Comment by oldnewthing** [comment]
Yup, should be `uint`, not `ulong`. Will fix in next refresh.
