### ISSUE TITLE
issue about AmsiProvider

### ISSUE THREAD

**Issue by Woniuke** [Microsoft/Windows-classic-samples#45]
Hello~!
 For some purpose , I want to monitor powershell script when it's running. 
According to the sourcecode from https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs  
I find the AMSI function will be called before compiling. So I make a test follow the instruction of AmsiProvider , But I can only see the function named CloseSession has been called , The scan function never have been called at all . The testing environment is Win10x86,16299,RS3

**Comment by oldnewthing** [comment]
Does the logging work if you use the instructions in the README? If so, then this is not an issue with the sample.
