### ISSUE TITLE
IAntimalwareProvider for VBS/JS?

### ISSUE THREAD

**Issue by Win32Query** [Microsoft/Windows-classic-samples#46]
I've been looking into the official sample on the Antimalware Scan Interface (AMSI) but I am having some difficulties with understanding something.

The sample I have been following: https://github.com/Microsoft/Windows-classic-samples/tree/master/Samples/AmsiProvider

A blog post by Microsoft which talks about using AMSI against malicious software (https://cloudblogs.microsoft.com/microsoftsecure/2017/12/04/windows-defender-atp-machine-learning-and-amsi-unearthing-script-based-attacks-that-live-off-the-land/) talks about using AMSI to capture deobfuscated JavaScript being executed by the script interpreter.

I've gone through the official documentation on MSDN but the information being provided is extremely bland in the sense that there is a very little documentation. The only other thing I could find which was of use aside from the documentation and the official sample demonstration was an article published by Cylance earlier this year (which mentions how to enable support for capturing VBA through AMSI): https://threatvector.cylance.com/en_us/home/how-to-implement-anti-malware-scanning-interface-provider.html

I've seen many external-source blog posts referencing to scanning of VBScript through AMSI - theoretically -, but the official sample only appears to capture PowerShell execution.

**Question: is there a way to capture VBScript/JavaScript or anything else aside from PowerShell and VBA? If so, are there any resources to assist in understanding how one should do this?**

It's definitely a possibility that I am doing something wrong - or have missed an obvious elephant in the room - and that the official sample is already capable of capturing VBScript and JavaScript. It'd be definitely helpful to get some assurance if this is the case.

Have a nice day!

**Comment by oldnewthing** [comment]
This is a question about the feature itself, not an issue with the sample. [The blog entry that announced AMSI](https://cloudblogs.microsoft.com/microsoftsecure/2015/06/09/windows-10-to-offer-application-developers-new-malware-defenses/?source=mmpc) contains contact information.
