### ISSUE TITLE
corrupt source files

### ISSUE THREAD

**Issue by dbremner** [Microsoft/Windows-classic-samples#5]
Hi, 

it looks like some of the files encoded as UTF-16LE were corrupted by git's line ending conversion. The attached image shows the result of opening Windows-classic-samples\Samples\PowerShell\Host\Host06\cs\Host06.cs in Visual Studio.
![image](https://cloud.githubusercontent.com/assets/101516/15910372/632c596e-2d7f-11e6-8d67-a06c9e204f2f.png)

I have also attached a list of files with [inconsistent line endings](https://github.com/Microsoft/Windows-classic-samples/files/305681/inconsistent_line_endings.txt).

[libgit2 bug  1002](https://github.com/libgit2/libgit2/issues/1009) discusses git's lack of support for UTF16

Regards,
David

**Comment by oldnewthing** [comment]
Thanks for the report. I'll try to patch things up by uncorrupting the file and then converting to UTF-8.

**Comment by oldnewthing** [comment]
Fixed in today's update. Thanks for reporting.
