### ISSUE TITLE
Gallery.xml of WindowsRibbon/Gallery is missing

### ISSUE THREAD

**Issue by ysc3839** [Microsoft/Windows-classic-samples#57]
Readme says:
https://github.com/Microsoft/Windows-classic-samples/blob/9e116e87e7b6ab4a530aa63596fb13165b56812b/Samples/Win7Samples/winui/WindowsRibbon/Gallery/ReadMe.txt#L9
However gallery.xml is missing.

**Comment by oldnewthing** [comment]
It appears that [it has always been missing](https://www.microsoft.com/en-us/download/details.aspx?id=9620). The original gallery sample [is also missing the file](https://github.com/pauldotknopf/WindowsSDK7-Samples/tree/master/winui/WindowsRibbon/Gallery).

**Comment by ysc3839** [comment]
The original gallery sample is not missing.
https://github.com/pauldotknopf/WindowsSDK7-Samples/blob/master/winui/WindowsRibbon/Gallery/CPP/gallery.xml
