### ISSUE TITLE
WpdApiSample error

### ISSUE THREAD

**Issue by LemonPG** [Microsoft/Windows-classic-samples#61]
error c2065; 'CLSID_PortableDeviceFTM' : undeclared identifier DeviceEnumeration.cpp 399  

How to fix it?

**Comment by oldnewthing** [comment]
This is an old Windows 7 sample. The Windows 7 samples are preserved for archival purposes, but are not actively supported. You can try to fix it yourself and create a pull request.

**Comment by oldnewthing** [comment]
I don't have this problem. CLSID_PortableDeviceFTM is defined in portabledeviceapi.h. The line number will vary depending on what version of the SDK you are using.

```
EXTERN_C const CLSID CLSID_PortableDeviceFTM;
```

In the Windows 8. 1 SDK, it's on line 3465.In the Windows 10 SDK, it's line 3464.
