### ISSUE TITLE
AmsiStream sample fails with E_INVALIDARG for large files

### ISSUE THREAD

**Issue by fschmied** [Microsoft/Windows-classic-samples#62]
When calling the AmsiStream sample with a large file, it fails with HRESULT 0x80070057 (E_INVALIDARG). Experimentation shows that files up to 16 MB (`CONTENT_SIZE` of 16777216) are supported, but larger files lead to this error.

Is this a bug in the sample implementation or a limitation of the AMSI interface/its Windows Defender implementation? After all, the `CONTENT_SIZE` attribute is documented to be a 64 bit value?

An interesting observation: `IAmsiStream::Read` is always called with a buffer that's exactly as large as `CONTENT_SIZE`, which isn't exactly the kind of streaming I thought it would do.

**Comment by oldnewthing** [comment]
A caller is welcome to pass a buffer of any size to IAmsiStream::Read. I think you're really talking about how the antimalware provider uses the AmsiStream sample, not how the sample itself behaves. For questions about how the antimalware provider uses the IAmsiStream interface, you'll have to ask the antimalware provider. The sample is doing what the provider is asking it to do.

**Comment by fschmied** [comment]
@oldnewthing The sample itself fails when it's called with a path to a file whose size is larger than 16 MB on a vanilla Windows 10 system on which I didn't tamper with the registered AMSI providers. If you're positive that the sample does not have a bug, I can conclude that the provider registered on a plain Windows 10 system does not support scanning streams larger than 16 MB?

**Comment by oldnewthing** [comment]
Yes, from what I can tell, the 16MB limitation is in the platform, not in the sample.

**Comment by drauch** [comment]
So, just to be sure, you are saying that the Microsoft-internal Windows Defender AMSI provider implementation is not able to scan files bigger than 16MB?

**Comment by oldnewthing** [comment]
I'm saying that that is what it appears to be. The sample itself can handle streams larger than 16MB.
