### ISSUE TITLE
Getting error  cannot convert argument 4 from 'LPITEMIDLIST *' to 'LPCITEMIDLIST *'  in CreateShellItemArrayOfSampleFiles, FileOperationSample.cpp

### ISSUE THREAD

**Issue by anubitum** [microsoft/Windows-classic-samples#64]
cannot convert argument 4 from 'LPITEMIDLIST *' to 'LPCITEMIDLIST *' 
on this line of code:
hr = SHCreateShellItemArray(NULL, psfSampleSrc, c_cMaxFilesToCreate, &rgpidlChildren[0], &psia);

**Comment by jiangsheng** [comment]
cannot reproduce with Visual Studio 2019 and Windows SDK 10.0.18362.0

**Comment by oldnewthing** [comment]
You get this error if you delete the `#define STRICT_TYPED_ITEMIDS` at the top of the `FileOperationSample.cpp` file. So don't do that.
