### ISSUE TITLE
samplewrapexistingcredentialprovider is not displayed in Windows7

### ISSUE THREAD

**Issue by sibiarunachalam** [microsoft/Windows-classic-samples#65]
I am exploring windows credential providers.
So, I have started with this samples https://github.com/Microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples/security/credentialproviders

**Build environment**
Windows 10 - 64 bit
Visual Studio 2017

**Build the project**
1. Open the project file .sln in IDE
2. It prompted to migrate the files, so I click Ok
3. I have built it for both 32 and 64
4. It built successfully

**What I have done**
1. I have installed respective vcredist.exe 
1. I have followed the instructions mentioned in respective samples
2. sampleallcontrolscredentialprovider works in both Win 10(64) and Win 7(32)
3. samplewrapexistingcredentialprovider works in Win 10(64) only, but not in Win 7(32)
4. No error displayed

**What is expected**
1. The tile "Local or domain account password..." should be displayed in Windows7 login screen along with other tiles

**Comment by oldnewthing** [comment]
Sorry, Windows 7 exited support on April 9, 2013.
