### ISSUE TITLE
Source file mistakenly recognized as binary file.

### ISSUE THREAD

**Issue by zhaobenx** [Microsoft/Windows-classic-samples#68]
In the cloud mirror project, three file are mistakenly recognized as binary file.

![image](https://user-images.githubusercontent.com/23143530/54257973-8b0e5180-4537-11e9-977a-aa5df8b31f81.png)
So when I clone this repo and open in my text editor, there are some errors. E.g. 
![image](https://user-images.githubusercontent.com/23143530/54258091-ee987f00-4537-11e9-86f6-b7b9130e108d.png)
![image](https://user-images.githubusercontent.com/23143530/54258120-03751280-4538-11e9-8526-137161afb28f.png)

**Comment by oldnewthing** [comment]
Yikes. Thanks for reporting.

**Comment by oldnewthing** [comment]
And thanks for fixing!

**Comment by zhaobenx** [comment]
You are welcome.
