### ISSUE TITLE
incorrect documentation: enabling ProjFS

### ISSUE THREAD

**Issue by verdy-p** [Microsoft/Windows-classic-samples#70]
The presentation page instructs us to run the following command in PowerShell to enable the ProjFS feature:

```Enable-WindowsOptionalFeature -Online -FeatureName ProjFS-Client -NoRestart```

But this feature name is not correct in windwos 10, as the command returns the error:

```Enable-WindowsOptionalFeature : ProjFS-Client : feature name unknown.```

The ProjFS support is installable using the "Control Panel>Programs & features>Add/remove Windows features". Note: It is still not proposed in the Settings Panel (which only focuses on basic features for standard users, such as language and fonts support, but not system components for virtualization, like ProjFS, Containers or Hyper-V).

Can you fix the doc with the correct Feature name to use in PowerShell ? Or if this feature requires adding another dependant component (to add it to the local repository of features that can then be enabled) give hints about which powershell command can make this check (notably does it require installing another package name?)

Note: adding the `-All` parameter to the command does not work, we still get an unknown feature name error.

I'm running Windows 10 Pro.

Note: using ```Get-WindowsOptionalFeature -Online``` in PowerShell (from an administrator account) to list all the provisioned features (enabled or disable) I noted that the feature is **actually named** `Client-ProjFS`, **not** `ProjFS-Client`.

So I suggest you add a link to Microsoft's documentation for [```Get-WindowsOptionalFeature```](https://docs.microsoft.com/fr-fr/previous-versions/windows/powershell-scripting/dn376470(v%3dwps.630)) and for [```Enable-WindowsOptionalFeature```](https://docs.microsoft.com/fr-fr/previous-versions/windows/powershell-scripting/dn376466(v%3dwps.630)).

Note that the doc is also no longer maintained (according to the top banner). It's very likely that the installation of optional features is under pending changes (due to the different integration with the legacy control panel, where all features provisioned by Windows 10 are listed, but not all in the Settings panel, which is provisioned by Windows Update and other software management and inventory systems; it's very likely that there are now other filters, for other sources, and probably new naming conventions). Still today, the feature name must be fixed, because this is still the one by which it is known (and there's still no evident way to find/enumerate the available optional packages/features, not event a web service (similar to those for Debian/APT packages for Linux where you can also add/remove providers and define possible mirrors/proxies or additional provider signatures for approved components, somrtyhing that is also needed in Windows for corporate environement with their own WSUS repository and cache with approved versions and dependencies).

**Comment by grossag** [comment]
This was very confusing. It would be nice to fix this and update https://docs.microsoft.com/en-us/windows/desktop/projfs/enabling-windows-projected-file-system

**Comment by ryan-roberts** [comment]
@GrantMeStrength John is this something you can assist with? At least for the documentation that grossag links to?

**Comment by verdy-p** [comment]
Grossag reported the same link I reported too (1st one before the 2nd one)

**Comment by cgallred** [comment]
@verdy-p you are correct, sorry about that!  I'll see about fixing it.

**Comment by cgallred** [comment]
Note that the referenced PR (#73) is for the sample's README.  I've filed a related issue in the docs repo: MicrosoftDocs/win32-pr#37.

**Comment by oldnewthing** [comment]
Fixed by #73.
