### ISSUE TITLE
TouchInputDirectManipulation example crashes on Windows 10

### ISSUE THREAD

**Issue by nesdnuma** [microsoft/Windows-classic-samples#71]
Hello,

I've retargeted this example for Windows 10 (v10.0.17763.0) and compiled it in Visual Studio Community 2017 (v15.9.7) successfully, however when I try to run the application it crashes immediately after opening of the window.

**Comment by oldnewthing** [comment]
I can't repro with 10.0.17763.0 + VS 2017 15.9.12, building as Debug|Win32, launches fine on 1903. You'll have to provide more details, like a stack trace with line numbers, or details of the nature of the crash.
