### ISSUE TITLE
[AmsiProvider] Compilation of the 64bit version fails

### ISSUE THREAD

**Issue by 0xcpu** [microsoft/Windows-classic-samples#72]
`32bit` version compiles without any problem.
Trying to compile `64bit` version results in the following error:
```
1>AmsiProvider.obj : error LNK2019: unresolved external symbol RoOriginateError referenced in function "public: virtual long __cdecl Microsoft::WRL::SimpleClassFactory<class SampleAmsiProvider,0>::CreateInstance(struct IUnknown *,struct _GUID const &,void * *)" (?CreateInstance@?$SimpleClassFactory@VSampleAmsiProvider@@$0A@@WRL@Microsoft@@UEAAJPEAUIUnknown@@AEBU_GUID@@PEAPEAX@Z)
1>{REDACTED PATH}\Windows-classic-samples-master\Samples\AmsiProvider\x64\Debug\AmsiProvider.dll : fatal error LNK1120: 1 unresolved externals
```

Adding `runtimeobject.lib` as an additional linker dependency doesn't solve the issue(taken from https://github.com/Microsoft/Windows-classic-samples/issues/40).
My environment:
```
MS VS 2017 Version 15.9.11
Microsoft Windows 10 Enterprise 64 bit, 10.0.17763 Build 17763
Windows SDK version 10.0.17763.0
```

Please help me understand what is the issue and provide a solution.
Thank you!

**Comment by oldnewthing** [comment]
Ah, the `Debug` build adds `windowsapp.lib;` but the Retail build doesn't. Need to add it to all flavors.

**Comment by oldnewthing** [comment]
Will be fixed in next update. Thanks.
