### ISSUE TITLE
MFPlayer is missing for running evrpresenter sample

### ISSUE THREAD

**Issue by fujii** [microsoft/Windows-classic-samples#75]
EVRPresenter sample needs MFPlayer, not MFPlayer2.

https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples/multimedia/mediafoundation/evrpresenter

> 3. Build and run the MFPlayer sample.
> 4. From the File menu, select Open File
> 5. In the Open File dialog, check "Custom EVR Presenter."

**Comment by oldnewthing** [comment]
Fixed in next refresh.

**Comment by fujii** [comment]
Oh, no. The change just modified Readme.txt.
MFPlayer2 doesn't have "Custom EVR Presenter" checkbox.

**Comment by fujii** [comment]
There is no reopen button. Filed another issue. https://github.com/microsoft/Windows-classic-samples/issues/99

**Comment by gast128** [comment]
Looking for exemplary code to use the EVR presenter. Microsoft recommends:
- see the EVRPlayer. Unfortunately this is on the Windows SDK 6.1 which is removed from download.
- use the MFPlayer then. This is on the Windows SDK 7 but also removed from github and replaced by MFPlayer2 which doesn't have any EVR presenter code.
