### ISSUE TITLE
Breakpoints of CloudMirrow are not hit

### ISSUE THREAD

**Issue by LokiMidgard** [microsoft/Windows-classic-samples#77]
I try to understand the CloudMirrow example and tried to add some breakpoits.

But those will not hit. If I set breakpoints after the process started, they are not valid (No symbols loaded).

I don't think I changed anything from the standard sample.

Using VS 2019 16 .2.0 preview 2.0

**Comment by LokiMidgard** [comment]
I think this has todo with the packaging project. When starting the actuall c++ project I'll hit the breakpoints.

But I must remove the `winrt::Windows::Storage::ApplicationData::Current().LocalSettings().Values()` everything else seems to work.

**Comment by oldnewthing** [comment]
You can work around the problem by running without debugging, and then attaching a debugger later.

**Comment by luedersj** [comment]
This is related to the packaging for desktop bridge/centennial. You can run without deploying the package but the some of the handlers will not be available since those are declared in the appx. I'll flow up with the centennial team on my this debug scenario does not work.
