### ISSUE TITLE
iphdrinc工程的注释问题

### ISSUE THREAD

**Issue by kouzhudong** [microsoft/Windows-classic-samples#78]
in line 513 at file:\Windows-classic-samples\Samples\Win7Samples\netds\winsock\iphdrinc\rawudp.c

// Function: CompouteUdpPsuedoHeaderChecksumV6

is should be:

// Function: ComputeUdpPseudoHeaderChecksumV6

也就是注释的函数名和实际的函数名不符，属于笔误。

https://correy.webs.com

**Comment by oldnewthing** [comment]
Will fix in next update.
