### ISSUE TITLE
rcvall工程的一处笔误。

### ISSUE THREAD

**Issue by kouzhudong** [microsoft/Windows-classic-samples#79]
in line 64 at Windows-classic-samples\Samples\Win7Samples\netds\winsock\rcvall\iphdr.h

is 

typedef struct tpc_hdr

is should be:

typedef struct tcp_hdr

是不是笔误？

再一个：一些SDK中的netiodef.h已经定义tcp_hdr.

https://correy.webs.com

**Comment by oldnewthing** [comment]
Fixed in next refresh.
