### ISSUE TITLE
Sample project doesn't produce any executable

### ISSUE THREAD

**Issue by dushabaev** [Microsoft/Windows-classic-samples#8]
[DX11VideoRenderer](https://github.com/Microsoft/Windows-classic-samples/tree/master/Samples/DX11VideoRenderer) produce only **DX11VideoRenderer.dll**. There is no executable file in **Debug** folder, however according to the [README.md](https://github.com/Microsoft/Windows-classic-samples/blob/master/Samples/DX11VideoRenderer/README.md) it has to be there.

**Comment by oldnewthing** [comment]
That text appears to be boilerplate in all the README, but it doesn't apply to this sample. I'll remove it.

**Comment by oldnewthing** [comment]
Correct instructions are

1. Register the DLL by running the command `regsvr32 DX11VideoRenderer.dll` from an elevated command prompt.
2. Run [the `topoedit.exe` program from the Windows SDK](https://docs.microsoft.com/en-us/windows/desktop/medfound/topoedit).
3. From the Topology menu, select "Add DX11 Video Renderer."
4. When you are finished using the sample, unregister the DLL by running the command `regsvr32 /u DX11VideoRenderer.dll` from an elevated command prompt.

I will update the README.
