### ISSUE TITLE
Is there a way to turn off auto focus and auto exposure with Windows Media Foundation?

### ISSUE THREAD

**Issue by jialiuBellus3d** [microsoft/Windows-classic-samples#80]
I can accept auto focus and auto exposure during preview stage, but want to turn them off once capture started.

Thanks

**Comment by oldnewthing** [comment]
This doesn't appear to be about a problem with a sample, but rather a question about the underlying OS functionality. You can use the [Windows Dev Center: Desktop Development forum](https://social.msdn.microsoft.com/Forums/Windowsdesktop/en-us/home).
