### ISSUE TITLE
Unable to compile after upgrade to Windows 10 1903

### ISSUE THREAD

**Issue by ToreDemant** [microsoft/Windows-classic-samples#83]
First reported here: https://github.com/WindowsNotifications/desktop-toasts/issues/14

After upgrading to Windows 10 1903 I am no longer able to compile the DesktopToasts example.
I am getting the following warnings:
The referenced component 'Windows.Data' could not be found.
The referenced component 'Windows.Foundation' could not be found.
The referenced component 'Windows.UI' could not be found.
And errors where code is dependent on the above assemblies.

These files were earlier in system32 but seems to have been removed from 1903. I have not been able to fin a nuget package that includes them.

I have tried Visual Studio 15.9.13 and 16.0.2 to 16.1.4 but same issue in all.
I have also been having problems building the progress example on a Windows 2016 build server: https://stackoverflow.com/questions/55899493/toastnotification-does-not-contain-a-definition-for-data-on-windows-server-2
Downgrade to Windows 10 1809 makes the project compile successfully again.

**Comment by oldnewthing** [comment]
This is not a question about a sample in this repo.

**Comment by oldnewthing** [comment]
It seems you can work around it by going to Add Reference, Browse, then pick

```
C:\Program Files (x86)\
    Windows Kits\
        10\
            References\
                10.0.17763.0\
                    Windows.Foundation.FoundationContract\
                        3.0.0.0\
                            Windows.Foundation.FoundationContract.winmd
```

and

```
C:\Program Files (x86)\
    Windows Kits\
        10\
            References\
                10.0.17763.0\
                    Windows.Foundation.UniversalApiContract\
                        7.0.0.0\
                            Windows.Foundation.UniversalApiContract.winmd
```

**Comment by ToreDemant** [comment]
This relates to the sample found here: https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/DesktopToasts/CS

Am I in the wrong place?

**Comment by ToreDemant** [comment]
Thank you for the workaround.

**Comment by oldnewthing** [comment]
Sorry, when you said this was an issue in the WindowsNotifications project, didn't realize that a copy of the project was also included in this repo.

**Comment by ToreDemant** [comment]
You wrote that using the winmd files where a work around - does that mean that another solution will come in the future?
I am trying to figure out how to reference these files without giving a full path as I need to have it working on different developer and build servers using one code base. If it is a temp workaround, then I might be able to skip this.

**Comment by oldnewthing** [comment]
I am just trying to help. These samples are not supported by me. I just collect them into a single repo for convenience.
