### ISSUE TITLE
Do not automatically start ComServer if app is not running and sync roots are still registered

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/Windows-classic-samples#84]
Opening the context menu if the CloudMirror package is not running forces a new instance to be created. Is it possible to stop this behavior and have a context menu if and only if the package is started by the user?

https://github.com/microsoft/Windows-classic-samples/blob/d42a2ea76a6d50c6790bbcf88a60de73cce069a9/Samples/CloudMirror/CloudMirrorPackage/Package.appxmanifest#L60

**Comment by AliveDevil** [comment]
Additional information: This only happens if `StorageProviderSyncRootManager::Unregister` is not called - thus the storage provider sync root is still registered, but the app is not running thus the app will be opened once the context menu is requested.

**Comment by luedersj** [comment]
We can consider this for future improvements. A production sync engine would need to be able to start the COM server without evoking UI.
