### ISSUE TITLE
DirectComposition_LayeredChildWIndow doesn't work properly on windows10 

### ISSUE THREAD

**Issue by SJRyu** [microsoft/Windows-classic-samples#85]
m_hControlChildWindow is always invisible.
I think the APIs in that project should work properly even on windows 10 too.
might be my pc is the problem but os version.

**Comment by niels1004** [comment]
I can reproduce this. I am on Windows 10 1903.

**Comment by oldnewthing** [comment]
Fixed by #118, will appear in next refresh.
