### ISSUE TITLE
Excaeption at Windows::Graphics::Holographic::IHolographicSpace2)->WaitForNextFrameReady()

### ISSUE THREAD

**Issue by dashingstag** [microsoft/Windows-classic-samples#88]
Access violation reading location at Windows::Graphics::Holographic::IHolographicSpace2)->WaitForNextFrameReady()

Headset is plugged in and things look normal in WMR portal before running.

Using Visual studios 2017 Windows SDK 10.0.17763.0
Windows version 1709 16299.726

**Comment by oldnewthing** [comment]
That line of code does not exist in any sample in this repo. (The only call to WaitForNextFrameReady is [here](https://github.com/microsoft/Windows-classic-samples/blob/340d6c8c537919663cb122d1a3cf76bed91c06f8/Samples/BasicHologram/cppwinrt/BasicHologramMain.cpp#L142), but the rest of the line doesn't match.) This sounds like a problem in your own program, not in the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
