### ISSUE TITLE
Enumerate Firewall Rules example contains a memory leak.

### ISSUE THREAD

**Issue by vldr** [microsoft/Windows-classic-samples#94]
I may be wrong on this but listed is the file which doesn't clean up after each enumeration which causes a massive memory leak.

The code calls QueryInterface to get FwRule but only the last enumerated FwRule is cleaned up and it is not cleaned up after each enumeration. 

https://github.com/microsoft/Windows-classic-samples/blob/master/Samples/Win7Samples/security/windowsfirewall/enumeratefirewallrules/EnumerateFirewallRules.cpp#L120

I believe the corrected while loop should resemble this:
````c
while (SUCCEEDED(hr) && hr != S_FALSE)
{
	var.Clear();
	hr = pVariant->Next(1, &var, &cFetched);

	if (S_FALSE != hr)
	{
		if (SUCCEEDED(hr))
		{
			hr = var.ChangeType(VT_DISPATCH);
		}

		if (SUCCEEDED(hr))
		{
			hr = (V_DISPATCH(&var))->QueryInterface(__uuidof(INetFwRule), reinterpret_cast<void**>(&pFwRule));
		}

		if (SUCCEEDED(hr))
                {
                      // Output the properties of this rule
                      DumpFWRulesInCollection(pFwRule);
                }

		// Release pFwRule
		if (pFwRule)
		{
			pFwRule->Release();
		}
	}
}

**Comment by vkrzv** [comment]
This example also doesn't free BSTRs obtained from get_Name, get_Description and other get_ methods.

**Comment by oldnewthing** [comment]
Almost. You also have to set `pFwRule = NULL;` after releasing, to avoid a double-release later. I'll get the BSTRs too.

**Comment by oldnewthing** [comment]
Fixed in next refresh. Thanks.
