### ISSUE TITLE
DpiAwarenessContext sample compilation error

### ISSUE THREAD

**Issue by WowItsDoge** [microsoft/Windows-classic-samples#96]
Hi,
there are some errors in the DpiAwarenessContext sample project.

I have openend it, but then visual Studio tells that targetver.h in the PluginDLL was not found.
So I deleted the file reference and clicked on "add existing element".
But in the PluginDLL folder was not this file, so I added it from the client folder.

Then when the compilation was started, no errors were produced.
But after pressing F5, the application crashes with the message
> "Exception thrown at 0x00007FFFD7772B10 (ntdll.dll) in DpiAwarenessContext.exe: 0xC0000139: Entry Point Not Found.".

Can you reproduce this error?

My system uses the current version of Windows 10 and Visual Studio 2017.

Regards,
Jan

**Comment by WowItsDoge** [comment]
Before the error is printed in visual studio, this message dialog is shown:

![image](https://user-images.githubusercontent.com/16211590/65686061-c4d22000-e063-11e9-9b20-59a333cb2515.png)

**Comment by oldnewthing** [comment]
The sample minimum requirements are incorrect. They should be Windows 10 version 1803 and SDK version 17134. I'll update the README.

**Comment by oldnewthing** [comment]
Updated in next refresh. Thanks.
